// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewApp.Api.DAL;

#nullable disable

namespace ReviewApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009091126_EnsureDefaultCollections")]
    partial class EnsureDefaultCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Achievement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Categories")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupCode");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Categories = 9,
                            Code = "MOVIE_MASTER_BRONZE",
                            Description = "Review 1 movie.",
                            GroupCode = "MOVIE_MASTER",
                            IconKey = "movie-master",
                            Metric = 0,
                            TargetValue = 1,
                            Tier = 0,
                            Title = "Movie Master"
                        },
                        new
                        {
                            ID = 2,
                            Categories = 9,
                            Code = "MOVIE_MASTER_SILVER",
                            Description = "Review 10 movies.",
                            GroupCode = "MOVIE_MASTER",
                            IconKey = "movie-master",
                            Metric = 0,
                            TargetValue = 10,
                            Tier = 1,
                            Title = "Movie Master"
                        },
                        new
                        {
                            ID = 3,
                            Categories = 9,
                            Code = "MOVIE_MASTER_GOLD",
                            Description = "Review 50 movies.",
                            GroupCode = "MOVIE_MASTER",
                            IconKey = "movie-master",
                            Metric = 0,
                            TargetValue = 50,
                            Tier = 2,
                            Title = "Movie Master"
                        },
                        new
                        {
                            ID = 4,
                            Categories = 10,
                            Code = "BINGE_WATCHER_BRONZE",
                            Description = "Review 1 series.",
                            GroupCode = "BINGE_WATCHER",
                            IconKey = "binge-watcher",
                            Metric = 1,
                            TargetValue = 1,
                            Tier = 0,
                            Title = "Binge Watcher"
                        },
                        new
                        {
                            ID = 5,
                            Categories = 10,
                            Code = "BINGE_WATCHER_SILVER",
                            Description = "Review 10 series.",
                            GroupCode = "BINGE_WATCHER",
                            IconKey = "binge-watcher",
                            Metric = 1,
                            TargetValue = 10,
                            Tier = 1,
                            Title = "Binge Watcher"
                        },
                        new
                        {
                            ID = 6,
                            Categories = 10,
                            Code = "BINGE_WATCHER_GOLD",
                            Description = "Review 50 series.",
                            GroupCode = "BINGE_WATCHER",
                            IconKey = "binge-watcher",
                            Metric = 1,
                            TargetValue = 50,
                            Tier = 2,
                            Title = "Binge Watcher"
                        },
                        new
                        {
                            ID = 7,
                            Categories = 12,
                            Code = "MUSIC_LOVER_BRONZE",
                            Description = "Review 1 piece of music.",
                            GroupCode = "MUSIC_LOVER",
                            IconKey = "music-lover",
                            Metric = 2,
                            TargetValue = 1,
                            Tier = 0,
                            Title = "Music Lover"
                        },
                        new
                        {
                            ID = 8,
                            Categories = 12,
                            Code = "MUSIC_LOVER_SILVER",
                            Description = "Review 10 pieces of music.",
                            GroupCode = "MUSIC_LOVER",
                            IconKey = "music-lover",
                            Metric = 2,
                            TargetValue = 10,
                            Tier = 1,
                            Title = "Music Lover"
                        },
                        new
                        {
                            ID = 9,
                            Categories = 12,
                            Code = "MUSIC_LOVER_GOLD",
                            Description = "Review 50 pieces of music.",
                            GroupCode = "MUSIC_LOVER",
                            IconKey = "music-lover",
                            Metric = 2,
                            TargetValue = 50,
                            Tier = 2,
                            Title = "Music Lover"
                        },
                        new
                        {
                            ID = 10,
                            Categories = 8,
                            Code = "CRITIC_BRONZE",
                            Description = "Write 10 reviews.",
                            GroupCode = "CRITIC",
                            IconKey = "critic",
                            Metric = 3,
                            TargetValue = 10,
                            Tier = 0,
                            Title = "Critic"
                        },
                        new
                        {
                            ID = 11,
                            Categories = 8,
                            Code = "CRITIC_SILVER",
                            Description = "Write 50 reviews.",
                            GroupCode = "CRITIC",
                            IconKey = "critic",
                            Metric = 3,
                            TargetValue = 50,
                            Tier = 1,
                            Title = "Critic"
                        },
                        new
                        {
                            ID = 12,
                            Categories = 8,
                            Code = "CRITIC_GOLD",
                            Description = "Write 100 reviews.",
                            GroupCode = "CRITIC",
                            IconKey = "critic",
                            Metric = 3,
                            TargetValue = 100,
                            Tier = 2,
                            Title = "Critic"
                        },
                        new
                        {
                            ID = 13,
                            Categories = 16,
                            Code = "CONVERSATION_STARTER_BRONZE",
                            Description = "Write 10 replies.",
                            GroupCode = "CONVERSATION_STARTER",
                            IconKey = "conversation-starter",
                            Metric = 4,
                            TargetValue = 10,
                            Tier = 0,
                            Title = "Conversation Starter"
                        },
                        new
                        {
                            ID = 14,
                            Categories = 16,
                            Code = "CONVERSATION_STARTER_SILVER",
                            Description = "Write 50 replies.",
                            GroupCode = "CONVERSATION_STARTER",
                            IconKey = "conversation-starter",
                            Metric = 4,
                            TargetValue = 50,
                            Tier = 1,
                            Title = "Conversation Starter"
                        },
                        new
                        {
                            ID = 15,
                            Categories = 16,
                            Code = "CONVERSATION_STARTER_GOLD",
                            Description = "Write 100 replies.",
                            GroupCode = "CONVERSATION_STARTER",
                            IconKey = "conversation-starter",
                            Metric = 4,
                            TargetValue = 100,
                            Tier = 2,
                            Title = "Conversation Starter"
                        },
                        new
                        {
                            ID = 16,
                            Categories = 8,
                            Code = "PROFESSIONAL_HATER_BRONZE",
                            Description = "Have 1 review scored 5.0 or less.",
                            GroupCode = "PROFESSIONAL_HATER",
                            IconKey = "professional-hater",
                            Metric = 5,
                            TargetValue = 1,
                            Tier = 0,
                            Title = "Professional Hater"
                        },
                        new
                        {
                            ID = 17,
                            Categories = 8,
                            Code = "PROFESSIONAL_HATER_SILVER",
                            Description = "Have 10 reviews scored 5.0 or less.",
                            GroupCode = "PROFESSIONAL_HATER",
                            IconKey = "professional-hater",
                            Metric = 5,
                            TargetValue = 10,
                            Tier = 1,
                            Title = "Professional Hater"
                        },
                        new
                        {
                            ID = 18,
                            Categories = 8,
                            Code = "PROFESSIONAL_HATER_GOLD",
                            Description = "Have 50 reviews scored 5.0 or less.",
                            GroupCode = "PROFESSIONAL_HATER",
                            IconKey = "professional-hater",
                            Metric = 5,
                            TargetValue = 50,
                            Tier = 2,
                            Title = "Professional Hater"
                        },
                        new
                        {
                            ID = 19,
                            Categories = 32,
                            Code = "CURATOR_BRONZE",
                            Description = "Create 1 collection of your own.",
                            GroupCode = "CURATOR",
                            IconKey = "curator",
                            Metric = 6,
                            TargetValue = 1,
                            Tier = 0,
                            Title = "Curator"
                        },
                        new
                        {
                            ID = 20,
                            Categories = 32,
                            Code = "CURATOR_SILVER",
                            Description = "Create 5 collections of your own.",
                            GroupCode = "CURATOR",
                            IconKey = "curator",
                            Metric = 6,
                            TargetValue = 5,
                            Tier = 1,
                            Title = "Curator"
                        },
                        new
                        {
                            ID = 21,
                            Categories = 32,
                            Code = "CURATOR_GOLD",
                            Description = "Create 10 collections of your own.",
                            GroupCode = "CURATOR",
                            IconKey = "curator",
                            Metric = 6,
                            TargetValue = 10,
                            Tier = 2,
                            Title = "Curator"
                        });
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Collection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityLevel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID", "Name")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.CollectionMedia", b =>
                {
                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("CollectionID", "MediaID");

                    b.HasIndex("MediaID");

                    b.ToTable("CollectionMedias");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalApiID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Media");

                    b.HasDiscriminator<int>("MediaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cons")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaID")
                        .HasColumnType("int");

                    b.Property<string>("Pros")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityLevel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MediaID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasTrigger("SetUpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.ReviewReply", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentReplyID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentReplyID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("UserID");

                    b.ToTable("ReviewReplies");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("AddDefaultCollection");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.UserAchievement", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("AchievementID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.HasKey("UserID", "AchievementID");

                    b.HasIndex("AchievementID");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.UserFollower", b =>
                {
                    b.Property<int>("FollowerID")
                        .HasColumnType("int");

                    b.Property<int>("FollowingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowerID", "FollowingID");

                    b.HasIndex("FollowingID");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Movie", b =>
                {
                    b.HasBaseType("ReviewApp.Api.DAL.Entities.Media");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Music", b =>
                {
                    b.HasBaseType("ReviewApp.Api.DAL.Entities.Media");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Series", b =>
                {
                    b.HasBaseType("ReviewApp.Api.DAL.Entities.Media");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Collection", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.CollectionMedia", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.Collection", "Collection")
                        .WithMany("CollectionMedias")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewApp.Api.DAL.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Review", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.ReviewReply", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.ReviewReply", "ParentReply")
                        .WithMany("ChildReplies")
                        .HasForeignKey("ParentReplyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReviewApp.Api.DAL.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentReply");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.UserAchievement", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.UserFollower", b =>
                {
                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReviewApp.Api.DAL.Entities.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.Collection", b =>
                {
                    b.Navigation("CollectionMedias");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.ReviewReply", b =>
                {
                    b.Navigation("ChildReplies");
                });

            modelBuilder.Entity("ReviewApp.Api.DAL.Entities.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");
                });
#pragma warning restore 612, 618
        }
    }
}
